"""
LexShield AI — PDF Export Service
==================================
Renders a completed legal draft (plain text) into a print-ready A4 PDF
using WeasyPrint.  Works entirely in-memory (io.BytesIO) — no temp files
on disk — so it is safe for stateless Cloud Run deployments.

Usage::

    from services.pdf_export import generate_complaint_pdf

    pdf_bytes = generate_complaint_pdf(
        draft_text       = "TO\\nTHE DISTRICT LABOUR COMMISSIONER …",
        doc_type         = "wage_theft",
        complainant_name = "Rahul Sharma",
    )
    # pdf_bytes is raw bytes — pass to StreamingResponse or write to file.
"""

import html
import io
import logging
import os
import sys

logger = logging.getLogger(__name__)

# ═══════════════════════════════════════════════════════════════════════════════
# WINDOWS DLL SETUP — WeasyPrint needs GTK/Pango/Cairo native libraries
# On Linux/Cloud Run these are installed via apt; on Windows we need to
# register the DLL directory explicitly so cffi can find them.
# ═══════════════════════════════════════════════════════════════════════════════
if sys.platform == "win32":
    _GTK_SEARCH_PATHS = [
        r"C:\msys64\ucrt64\bin",
        r"C:\msys64\mingw64\bin",
        r"C:\Program Files\GTK3-Runtime Win64\bin",
        r"C:\Program Files\Tesseract-OCR",
    ]
    for _dir in _GTK_SEARCH_PATHS:
        if os.path.isfile(os.path.join(_dir, "libgobject-2.0-0.dll")):
            os.add_dll_directory(_dir)
            logger.debug(f"[pdf_export] Registered DLL directory: {_dir}")
            break


# ═══════════════════════════════════════════════════════════════════════════════
# CATEGORY → DISPLAY TITLE  (mirrors _CATEGORY_LABELS in drafting_agent.py)
# ═══════════════════════════════════════════════════════════════════════════════

_DOC_TYPE_TITLES: dict[str, str] = {
    "wage_theft":             "Non-Payment / Withholding of Wages Complaint",
    "illegal_eviction":       "Illegal Eviction / Unlawful Dispossession Complaint",
    "cheque_bounce":          "Complaint under Section 138, Negotiable Instruments Act",
    "consumer_complaint":     "Consumer Complaint under Consumer Protection Act, 2019",
    "fir_complaint":          "Written Complaint for FIR Registration (BNSS Section 173)",
    "domestic_violence":      "Application under Protection of Women from Domestic Violence Act, 2005",
    "employment_termination": "Complaint for Wrongful / Illegal Employment Termination",
    "loan_default":           "Complaint against Lender / Bank (Loan Harassment / Unfair Recovery)",
}


# ═══════════════════════════════════════════════════════════════════════════════
# HTML TEMPLATE
# ═══════════════════════════════════════════════════════════════════════════════

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<style>
  @page {{
    size: A4;
    margin: 25mm;
    @bottom-center {{
      content: "Page " counter(page) " of " counter(pages);
      font-family: Georgia, "Times New Roman", serif;
      font-size: 9pt;
      color: #666;
    }}
  }}

  body {{
    font-family: Georgia, "Times New Roman", serif;
    font-size: 12pt;
    line-height: 1.6;
    color: #1a1a1a;
    margin: 0;
    padding: 0;
  }}

  .header {{
    text-align: center;
    border-bottom: 2px solid #333;
    padding-bottom: 12pt;
    margin-bottom: 18pt;
  }}

  .header h1 {{
    font-size: 14pt;
    font-weight: bold;
    margin: 0 0 4pt 0;
    text-transform: uppercase;
    letter-spacing: 0.5pt;
  }}

  .header .subtitle {{
    font-size: 10pt;
    color: #555;
    margin: 0;
  }}

  .draft-body p {{
    margin: 0 0 10pt 0;
    text-align: justify;
  }}

  /* Prevent verification / signature block from splitting across pages */
  .signature-block {{
    page-break-inside: avoid;
  }}

  .footer-note {{
    margin-top: 24pt;
    padding-top: 10pt;
    border-top: 1px solid #ccc;
    font-size: 9pt;
    color: #888;
    text-align: center;
  }}
</style>
</head>
<body>
  <div class="header">
    <h1>{title}</h1>
    <p class="subtitle">Generated by LexShield AI &mdash; For Review by Qualified Advocate</p>
  </div>

  <div class="draft-body">
    {body_html}
  </div>

  <p class="footer-note">
    This document was generated by LexShield AI for reference purposes.
    Please review with a qualified legal professional before filing.
  </p>
</body>
</html>
"""


# ═══════════════════════════════════════════════════════════════════════════════
# TEXT → HTML CONVERSION
# ═══════════════════════════════════════════════════════════════════════════════

def _text_to_body_html(draft_text: str) -> str:
    """
    Convert plain-text draft to HTML body content.

    Rules:
      1. HTML-escape all special characters (LLM output safety).
      2. Split on double newlines → <p> tags (paragraph breaks).
      3. Single newlines within a paragraph → <br> (preserve LLM line breaks).
      4. Wrap VERIFICATION / SIGNATURE blocks in a div with
         page-break-inside: avoid to prevent awkward page splits.

    This does NOT re-parse or re-format the legal text in any way —
    it preserves the LLM's formatting exactly as generated.
    """
    # Step 1: HTML-escape
    safe = html.escape(draft_text)

    # Step 2: Split on double newlines → paragraphs
    paragraphs = safe.split("\n\n")

    html_parts = []
    in_signature_block = False

    for para in paragraphs:
        # Convert single newlines to <br>
        content = para.strip().replace("\n", "<br>\n")
        if not content:
            continue

        # Detect signature / verification block start
        upper = content.upper()
        is_sig = any(marker in upper for marker in [
            "VERIFICATION",
            "SIGNATURE OF COMPLAINANT",
            "SIGNATURE OF APPLICANT",
            "SIGNATURE OF PETITIONER",
            "LIST OF ENCLOSURES",
            "LIST OF DOCUMENTS",
            "COMPLAINANT<BR>",
            "APPLICANT<BR>",
            "PETITIONER<BR>",
            "YOURS RESPECTFULLY",
            "YOURS FAITHFULLY",
        ])

        if is_sig and not in_signature_block:
            in_signature_block = True
            html_parts.append('<div class="signature-block">')

        html_parts.append(f"<p>{content}</p>")

    # Close signature block if opened
    if in_signature_block:
        html_parts.append("</div>")

    return "\n".join(html_parts)


# ═══════════════════════════════════════════════════════════════════════════════
# PUBLIC API
# ═══════════════════════════════════════════════════════════════════════════════

def generate_complaint_pdf(
    draft_text:       str,
    doc_type:         str,
    complainant_name: str,
) -> bytes:
    """
    Render a completed plain-text legal draft as a print-ready A4 PDF.

    Parameters
    ----------
    draft_text : str
        The full plain-text legal complaint/application as generated by the LLM.
    doc_type : str
        Category key (e.g. "wage_theft", "cheque_bounce").
    complainant_name : str
        Name of the complainant (used in the header subtitle).

    Returns
    -------
    bytes
        Raw PDF file content.  Does not write to disk.

    Raises
    ------
    Exception
        If WeasyPrint rendering fails (caller should catch and return 500).
    """
    from weasyprint import HTML

    title = _DOC_TYPE_TITLES.get(doc_type, doc_type.replace("_", " ").title())
    body_html = _text_to_body_html(draft_text)

    full_html = _HTML_TEMPLATE.format(
        title=html.escape(title),
        body_html=body_html,
    )

    buf = io.BytesIO()
    HTML(string=full_html).write_pdf(buf)
    buf.seek(0)
    return buf.read()
